config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/apps", to:"apps#index"
  get "/apps/tictactoe", as: "ttt"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/views/apps/index.html.erb
<h1>Welcome to Minic Inc.</h1>
<h3>select a project ot continue</h3>

app/views/apps/tictactoe.html.erb
<head>
<%= stylesheet_link_tag "tictactoe", "data-turbo-track": "reload" %>

</head>
<div id='game'>
  <h1>Tic-Tac-Toe</h1>

  <div id='container'>
    <button id="btw1"></button>
    <button id="btw2"></button>
    <button id="btw3"></button>
    <button id="btw4"></button>
    <button id="btw5"></button>
    <button id="btw6"></button>
    <button id="btw7"></button>
    <button id="btw8"></button>
    <button id="btw9"></button>
  </div>

</div>

<script src="<%= javascript_path 'tictactoe' %>"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Draft</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <header>
    <%= image_tag("Banner-980-300.png", :alt => "Banner") %>
    <ul>
      <li><a href=" <%= ttt_path %> ">Tic-Tac-Toe</a></li>
      <li><a href="">Restaraunt</a></li>
      <li><a href=""></a>Todo</li>
      <li><a href=""></a>Weather</li>
      <li><a href="">Testing</a></li>
      <li><a href="">Battleship</a></li>
    </ul>
  </header>
  <div class = "game_cont">
    <%= yield %>
  </div>
  <footer>
    <h3>serving you since 2023</h3>
  </footer>
  </body>
</html>